### ISSUE TITLE
Missing directory reverse-proxy

### ISSUE THREAD

**Issue by franji** [Azure/azure-iot-pcs-remote-monitoring-java#16]
# Type of issue

- [ ] Bug
- [ ] New feature
- [X ] Improvement

# Description

The directory of reverse-proxy submodule does not exist.
This element is present in the azure-iot-pcs-remote-monitoring-dotnet project.

**Comment by dluc** [comment]
@franji thanks for reporting the issue!

@ppathan I think we should make a repo for the proxy, similar to the SSL proxy, and link it via submodule in the 2 solutions, what do you think?

**Comment by ppathan** [comment]
Not in plan for next 6 months.
