### ISSUE TITLE
Simulation Agent - Unable to fetch the IoT device

### ISSUE THREAD

**Issue by brunohcfaria** [Azure/azure-iot-pcs-remote-monitoring-java#28]
# Type of issue

- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description

Whenever I try to deploy a remotemonitoring solution there is no data available on the Web GUI.
I ssh into the VM and get the log of the device-simulation-dotnet:1.0.0-preview.2 
Then I saw the following exception that may be the cause of data not being available on the Web GUI:

[ERROR][2017-11-13 17:35:33.396][SimulationAgent.16a35158-b7af-4873-aa3b-c3ec46d29ce0][Devices:CreateAsync] Unable to fetch the IoT device, {"deviceId":"Simulated.chiller-02.0","e":{"ExceptionFullName":"Microsoft.Azure.Devices.Common.Exceptions.IotHubException","ExceptionMessage":"Additional text found in JSON string after finishing deserializing object

# Steps to reproduce

1. pcs -t remotemonitoring -s basic -r java
2. Tried to see the data on the dashboard
3. No data available

# Expected behavior

...

[app_devicesimulation_1.txt](https://github.com/Azure/azure-iot-pcs-remote-monitoring-java/files/1467929/app_devicesimulation_1.txt)

# Current behavior

...

# Known workarounds

...

# Possible solution

...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Java JDK/JRE: ...

# Code to reproduce the bug

```
import org.junit.*;
import org.junit.experimental.categories.Category;

public class MyTest {

    @Test(timeout = 5000)
    public void TestToReproduceIssue() {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by dluc** [comment]
@brunohcfaria do you deploy the solution using the command line tool or IoT Suite? 

If you're using CLI, could you make sure you have the latest version, because looks like you're deploying an old version of Remote Monitoring. 

The latest version is 1.0.0-preview.3, it was released 2 weeks ago, and should fix the issues you are experiencing.
