### ISSUE TITLE
Storage Adapter repo tree that PCS is using has build errors.

### ISSUE THREAD

**Issue by jwendl** [Azure/azure-iot-pcs-remote-monitoring-java#51]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
The version of the storage adapter that the remote monitoring repository is pointing to has build errors when master does not. 
...

# Steps to reproduce
1. git clone --recurse on this repo
2. cd storage-adapter
3. ./scripts/build

# Expected behavior
Tests run with no error messages

# Current behavior
Error message

✘ jwendl  /c/Source/GitHub/azure-iot-pcs-remote-monitoring-java/storage-adapter  ➦ 0b16dd5 ●  ./scripts/build

### Running tests...
/c/Source/GitHub/azure-iot-pcs-remote-monitoring-java/storage-adapter/build.sbt:29: error: not found: value assemblyMergeStrategy
  assemblyMergeStrategy in assembly := {
  ^
/c/Source/GitHub/azure-iot-pcs-remote-monitoring-java/storage-adapter/build.sbt:58: error: not found: value PlayJava
  .enablePlugins(PlayJava)
                 ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q

# Known workarounds
Clone pcs-storage-adapter-java manually at master and try to make that work.

# Possible solution

# Context and Environment
* Operating System: Windows 10 using WSL Ubuntu 16.04
* GitHub branch: remote monitoring master
* Java JDK/JRE: 
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)

**Comment by ppathan** [comment]
@jwendl Can you confirm if this issue is still there?

**Comment by asdonald** [comment]
@jwendl We are going to close this issue. Please let us know if you are still running into issues.
