### ISSUE TITLE
Dashboard Error

### ISSUE THREAD

**Issue by prafullkotecha** [Azure/azure-iot-pcs-remote-monitoring-java#57]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
See attached screenshot
![azure-iot-solutions-java-remote-monitoring-local-dashboard](https://user-images.githubusercontent.com/563146/44449336-cc4f0c00-a5bb-11e8-8b2e-25395fda603e.png)

# Steps to reproduce
Followed the steps given [here](https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local)

# Expected behavior
Please see attached image from [this page](https://docs.microsoft.com/en-us/azure/iot-accelerators/quickstart-remote-monitoring-deploy)
![solutiondashboard-expanded](https://user-images.githubusercontent.com/563146/44449321-c0634a00-a5bb-11e8-872d-3bb70824515c.png)

**Comment by ppathan** [comment]
@zhang-hua Can you investigate it?

**Comment by asdonald** [comment]
@prafullkotecha Can you please reply with error logs from browser.

**Comment by asdonald** [comment]
@prafullkotecha Closing for no response. Please re-open and add logs if you see an issue.
