### ISSUE TITLE
Job execution failure

### ISSUE THREAD

**Issue by sushilraje** [Azure/azure-iot-pcs-remote-monitoring-java#59]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
Execute a firmware update job on the chillers from RM. The job seems to run (from the RM UI), but the firmware update is not reflected on the devicetwin and consequently on the UI.
 
While executing the job, the device simulation service throws an exception –
 
**"DataAsJson":"\"{}\"","e":{"ExceptionFullName":"Newtonsoft.Json.JsonSerializationException","ExceptionMessage":"Error converting value \"{}\" to type 'System.Collections.Generic.Dictionary`2[System.String,System.String]'**
 
On querying the IotHub, the job is reported as “Completed” although it has failure.

3 Issues 
1. Is device simulation reporting job failures to IotHub?
2. IotHubManager is escaping again already escaped string "JsonPaylod".
3. Job Status API reports status 7 (successful completion) of the job even if job has failed in device simulation

# Steps to reproduce
1. Deploy remote monitoring solutions (java basic deployment).
2. Run a Firmware update job for any of the device
3. View job status & then the device firmware on the devices tab

# Expected behavior
Job completion should be indicate successful or failed execution. 

# Current behavior
Failed jobs are reported as completed.

# Known workarounds
None

# Possible solution

# Context and Environment
* Operating System: Linux
* GitHub branch: master
* Java JDK/JRE: 1.8

# Code to reproduce the bug

**Comment by isaac73** [comment]
https://github.com/Azure/azure-iot-sdk-java/issues/327
