### ISSUE TITLE
Post Installation of Java based RM Accelerator , Application UI is not showing data

### ISSUE THREAD

**Issue by RaghuRamaswamy** [Azure/azure-iot-pcs-remote-monitoring-java#60]
# Type of issue
- [ ] Bug

# Description
Post successful installation of the RM Accelerator Java code base.. The UI is showing Error: unexpected character at line 1 column 1 of the JSON data

# Steps to reproduce

1. Complete installation
2. Launch the application  https://remotemonitoringpaygo.azurewebsites.net/dashboard
3. see Error: unexpected character at line 1 column 1 of the JSON data on the user

# Expected behavior
UI Should display default devices and telemetry data
...

# Current behavior
Error: unexpected character at line 1 column 1 of the JSON data
...

**Comment by ppathan** [comment]
Hi @RaghuRamaswamy Thanks for trying out the RM Java solution. 
We don't have access to your deployed solution. Can you confirm if you deployed it from www.azureiotsolutions.com? Also can you paste errors from browser window by pressing F12?

**Comment by RaghuRamaswamy** [comment]
Yes, have used https://www.azureiotsolutions.com/Accelerators

Here is error as seen on browser : 

{…}​message: "ajax error 500"​request: {…}​​async: true​​body: undefined​​createXHR: function createXHR()​​crossDomain: false​​headers: Object { Accept: "application/json", "Content-Type": "application/json", "Csrf-Token": "nocheck", … }​​method: "GET"​​responseType: "json"​​timeout: 20000​​url: "/config/v1/devicegroups"​​withCredentials: false​​__proto__: Object { … }​response: {…}​​Error: "java.lang.NullPointerException"​​__proto__: Object { … }​responseType: "json"​stack: ""​status: 500​xhr: XMLHttpRequest​​mozAnon: false​​mozSystem: false​​onabort: null​​onerror: function s()​​onload: null​​onloadend: null​​onloadstart: null​​onprogress: null​​onreadystatechange: function r()​​ontimeout: function n()​​readyState: 4​​response: Object { Error: "java.lang.NullPointerException" }​​responseType: "json"​​responseURL: "https://remotemonitoringpaygo.azurewebsites.net/config/v1/devicegroups"​​status: 500​​statusText: "Internal Server Error"​​timeout: 20000​​upload: XMLHttpRequestUpload { onloadstart: null, onprogress: null, onabort: null, … }​​withCredentials: false​​__proto__: XMLHttpRequestPrototype { open: open(), setRequestHeader: setRequestHeader(), send: send(), … }​__proto__: Object { constructor: t(), stack: "" } ajaxModels.js:20:4

**Comment by asdonald** [comment]
@RaghuRamaswamy  Can you please paste in the network response from the link you posted: https://remotemonitoringpaygo.azurewebsites.net/config/v1/devicegroups

**Comment by asdonald** [comment]
@ppathan Running into the same issue. Here's the deployment I just created: https://ashleybugcheck.azurewebsites.net/dashboard

**Comment by asdonald** [comment]
@asdonald  to update deployment and assign to Hua

**Comment by asdonald** [comment]
@asdonald  to use basic java.

**Comment by avneet723** [comment]
@asdonald does this still repro?

**Comment by asdonald** [comment]
No Repro
