### ISSUE TITLE
Document DB database accounts creation failure

### ISSUE THREAD

**Issue by muralim2576** [Azure/azure-iot-pcs-remote-monitoring-java#70]
# Type of issue 
- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description 
...while deploying the dotnet solution from cli, fails at provisioning stage documentDB/creatingdatabaseaccounts

**Found the below error on portal before the deployment is rolled back and every resource provisioned gets rolled back(deleted)**

{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"ServiceUnavailable\",\"message\":\"Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.\\r\\nActivityId: 
# Screenshot 
![image](https://user-images.githubusercontent.com/71292179/93138435-4856a800-f6df-11ea-8e75-2243069c1139.png)

# Steps to reproduce 
Follow instructions on the Microsoft website link below
https://docs.microsoft.com/en-gb/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-cli

# Expected behavior 

# Current behavior 
...

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

**Comment by miwolfms** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
